// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mstC
IntegerMatrix mstC(RObject d);
RcppExport SEXP _yea13_mstC(SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(mstC(d));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_yea13_mstC", (DL_FUNC) &_yea13_mstC, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_yea13(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
