# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Minimum spanning tree
#'
#' C++ implementation based on `ape::mst`.
#'
#' @param d An object of class `dist` containing finite distances.
#' @param debug Logical; print intermediate algorithm state.
#' @return A symmetric adjacency matrix of class `mst`.
#' @export
mst <- function(d, debug = FALSE) {
    .Call(`_yea13_mst`, d, debug)
}

