# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Minimum spanning tree
#' 
#' This is a C++ transcript of function \code{ape::mst} by Yvonnick Noel, Julien Claude, and Emmanuel Paradis, cf. \url{https://github.com/cran/ape/blob/master/R/mst.R}.
#'
#' @param d An object of type 'dist'.
#' @param debug logical, specifying if intermediate steps should be printed out.
#' @return An adjacency matrix belonging to class 'ape::mst'.
#' @export
mstC <- function(d, debug = FALSE) {
    .Call(`_yea13_mstC`, d, debug)
}

