# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Minimum spanning tree
#' 
#' This is a C++ transcript of function \code{mst} in package \code{ape} by Yvonnick Noel, Julien Claude, and Emmanuel Paradis, 
#' cf. \href(https://github.com/cran/ape/blob/master/R/mst.R){Github archive of mst.R}.
#'
#' @param d An object of type 'dist'.
#' @return An adjacency matrix belonging to class 'mst'.
#' @export
mstC <- function(d) {
    .Call(`_yea13_mstC`, d)
}

