#' Identify putative clusters
#'
#' @param yd A square Ypma dissimilarity matrix or a list of such matrices.
#' @param hs Numeric heights at which hierarchical trees should be cut.
#' @param result Return cluster-size thresholds (`"sizes"`) or cluster details
#'   (`"clusters"`).
#' @param p.value Numeric, calulate lower bound of permuted max. dissimilarity corresponding 
#'   to this value.
#' @return A data.frame describing clusters or permutation thresholds.
#' @export
y.clust <- function(yd, hs = c(2, 4, 6), result = c("sizes", "clusters"), p.value = 0.05) {
  result <- match.arg(result)
  if (!length(hs) || any(!is.finite(hs))) {
    stop("'hs' must contain one or more finite cut heights.", call. = FALSE)
  }

  # `cl` is a helper function that returns a data frame with clusters 
  # corresponding to a given height h
  cl <- function(d0, h) {
    # check if d0 corresponds to square ypma dissimilarity matrix
    if (!is.matrix(d0) || nrow(d0) != ncol(d0)) {
      stop("Each element of 'yd' must be a square matrix.", call. = FALSE)
    }
    # if just one row, return empty data frame
    if (nrow(d0) < 2L) return(data.frame())
    # creata a dendrogram from d0
    y.h <- stats::hclust(stats::as.dist(d0))
    
    # cut it up according to height h
    # note that h is arbitrary, specific to a dendrogram, and not portable
    # a better solution is needed
    # ideally one would need a range of heights where the lowest height
    # at least includes one cluster with two data points
    memberships <- stats::cutree(y.h, h = h)
    # the following line only works if names exist, i.e. if matrix d0 has
    # row and column names!
    # insert check in future versions!
    groups <- split(names(memberships), memberships)
    # only retain groups whith at least two data points present:
    groups <- groups[lengths(groups) > 1L]
    # if no group contains more than one data point return an empty data frame:
    if (!length(groups)) return(data.frame())

    # return resulting data frame:
    data.frame(
      cluster.no = seq_along(groups),   # the cluster number starting with 1
      size = lengths(groups),           # the number of data points per cluster
      ids = I(unname(groups)),      # the ids of the data points; as unname(groups) is a list, I facilitates placement into a data frame column
      max.diss = vapply(groups, function(ids) max(d0[ids, ids, drop = FALSE]), numeric(1)), # this calculates the maximum dissimilarity observerd for this cluster
      stringsAsFactors = FALSE
    )
  }

  # ycf applies above function `cl` for different heights (given in hs)
  ycf <- function(y) {
    # apply cl for each height in hs present.
    # pieces is a list of data frames
    pieces <- lapply(hs, function(h) cl(y, h))
    # remove data frames without rows - this happens if no clusters have been found 
    pieces <- pieces[vapply(pieces, nrow, integer(1)) > 0L]
    # if no data frames remain return an empty data frame:
    if (!length(pieces)) return(data.frame())
    # combine the remaining data frames into a big one to return:
    do.call(rbind, pieces)
  }

  # convert yd to list even if only a single matrix has been supplied
  matrices <- if (is.list(yd)) yd else list(yd)
  # generate a list of data frames generated by ycf, see above
  pieces <- lapply(matrices, ycf)
  # only retain data frames in the list with rows > 0
  pieces <- pieces[vapply(pieces, nrow, integer(1)) > 0L]
  # if no data frames remain return a data frame scaffold with no data:
  if (!length(pieces)) {
    if (result == "sizes") {
      return(data.frame(size = integer(), `minimal max.diss` = numeric(), check.names = FALSE))
    }
    return(data.frame(cluster.no = integer(), size = integer(), ids = I(list()), max.diss = numeric()))
  }

  # combine data frames
  yc <- do.call(rbind, pieces)
  # remove row names:
  rownames(yc) <- NULL
  # as many data frames each with cluster.no beginning at 1 have potentially
  # been combined, set new cluster numbers - for each row
  yc$cluster.no <- seq_len(nrow(yc))

  # "sizes" means that results are grouped by size number
  if (result == "sizes") {
    # group by size and return the minimum max.diss per cluster size
    mins <- tapply(yc$max.diss, yc$size, min)
    # also calculate lower significance bound corresponding to p.value 
    sig <- tapply(yc$max.diss, yc$size, function(mxd) as.numeric(quantile(mxd, p.value)))
    # return a data frame with cluster size,  minimal max.diss and significance bound found:
    data.frame(size = as.integer(names(mins)), `minimal max.diss` = as.numeric(mins), `sig. max.diss` = sig, check.names = FALSE)
  } else {
    # alternatively, return the data frame detailing all the clusters found:
    yc
  }
}
